name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7]
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pytest pytest-mock==1.10.4 pytest-cov coverage requests six futures
      - name: Install enum
        run: pip install enum34
        if: ${{ matrix.python-version == 2.7 }}
      - name: Install python/typing
        run: pip install typing
        if: ${{ matrix.python-version == 3.4 }} 
      - name: Test with pytest
        run: pytest
